version: "3.9"

services:
  webapi:
    build:
      context: .
      dockerfile: ./FashionClothesAndTrends.WebAPI/Dockerfile
    restart: always
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPass@word90_
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultDockerDbConnection=Server=sql_server2022,1433;Database=FashionClothesAndTrendsDB;User Id=sa;Password=MyPass@word90_;MultipleActiveResultSets=true;TrustServerCertificate=True
      - Redis__ConnectionString=redis:6379
    links:
      - sql
      - redis
    depends_on:
      - sql
      - redis
    networks:
      - app_network
    volumes:
      - ~/.aspnet/https:/https:ro

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--timeout", "0"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server2022
    environment:
      SA_PASSWORD: "MyPass@word90_"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: CMD /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MyPass@word90_ -Q "SELECT 1" || exit 1
      timeout: 20s
      retries: 10
      start_period: 10s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge