FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci --prefer-offline --legacy-peer-deps

COPY . .

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]
